"""Pre-computed expected counts and odds for target regions at the pre-final-week cutoff.

Generated by backend/scripts/gen_pre_final_week_fixtures.py from 2025 season data.
Cutoffs: 1A–4A on or before 2025-10-24; 5A–7A on or before 2025-10-31.
"""

from collections import Counter

from backend.helpers.data_classes import StandingsOdds

PRE_FINAL_WEEK_EXPECTED: dict[tuple[int, int], dict] = {
    # Region 1-1A  (2 remaining games, denom=4)
    # Teams (alphabetical): Biggersville, Smithville, Thrasher, Tupelo Christian
    # Cutoff: 2025-10-24
    # Actual seeds: Biggersville / Tupelo Christian / Smithville / Thrasher
    (1, 1): {
        "denom": 4,
        "first_counts":  Counter({'Biggersville': 4}),
        "second_counts": Counter({'Tupelo Christian': 2, 'Smithville': 2}),
        "third_counts":  Counter({'Smithville': 2, 'Tupelo Christian': 2}),
        "fourth_counts": Counter({'Thrasher': 4}),
        "odds": {
        'Biggersville': StandingsOdds(school='Biggersville', p1=1.0, p2=0.0, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Smithville': StandingsOdds(school='Smithville', p1=0.0, p2=0.5, p3=0.5, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Thrasher': StandingsOdds(school='Thrasher', p1=0.0, p2=0.0, p3=0.0, p4=1.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Tupelo Christian': StandingsOdds(school='Tupelo Christian', p1=0.0, p2=0.5, p3=0.5, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        },
    },

    # Region 2-1A  (2 remaining games, denom=4)
    # Teams (alphabetical): Ashland, Falkner, H. W. Byers, Potts Camp
    # Cutoff: 2025-10-24
    # Actual seeds: Falkner / H. W. Byers / Potts Camp / Ashland
    (1, 2): {
        "denom": 4,
        "first_counts":  Counter({'Falkner': 2.9166666666666665, 'Potts Camp': 1.0833333333333333}),
        "second_counts": Counter({'H. W. Byers': 2.833333333333333, 'Falkner': 1.0833333333333333, 'Potts Camp': 0.08333333333333333}),
        "third_counts":  Counter({'Potts Camp': 2.833333333333333, 'Ashland': 1.0833333333333333, 'H. W. Byers': 0.08333333333333333}),
        "fourth_counts": Counter({'Ashland': 2.9166666666666665, 'H. W. Byers': 1.0833333333333333}),
        "odds": {
        'Ashland': StandingsOdds(school='Ashland', p1=0.0, p2=0.0, p3=0.2708333333333333, p4=0.7291666666666666, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Falkner': StandingsOdds(school='Falkner', p1=0.7291666666666666, p2=0.2708333333333333, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'H. W. Byers': StandingsOdds(school='H. W. Byers', p1=0.0, p2=0.7083333333333333, p3=0.020833333333333332, p4=0.2708333333333333, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Potts Camp': StandingsOdds(school='Potts Camp', p1=0.2708333333333333, p2=0.020833333333333332, p3=0.7083333333333333, p4=0.0, p_playoffs=0.9999999999999999, final_playoffs=1.0, clinched=True, eliminated=False),
        },
    },

    # Region 3-1A  (2 remaining games, denom=4)
    # Teams (alphabetical): Calhoun City, Okolona, Vardaman, West Lowndes
    # Cutoff: 2025-10-24
    # Actual seeds: Calhoun City / West Lowndes / Okolona / Vardaman
    (1, 3): {
        "denom": 4,
        "first_counts":  Counter({'West Lowndes': 2, 'Calhoun City': 2}),
        "second_counts": Counter({'Calhoun City': 2, 'West Lowndes': 2}),
        "third_counts":  Counter({'Vardaman': 2, 'Okolona': 2}),
        "fourth_counts": Counter({'Okolona': 2, 'Vardaman': 2}),
        "odds": {
        'Calhoun City': StandingsOdds(school='Calhoun City', p1=0.5, p2=0.5, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Okolona': StandingsOdds(school='Okolona', p1=0.0, p2=0.0, p3=0.5, p4=0.5, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Vardaman': StandingsOdds(school='Vardaman', p1=0.0, p2=0.0, p3=0.5, p4=0.5, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'West Lowndes': StandingsOdds(school='West Lowndes', p1=0.5, p2=0.5, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        },
    },

    # Region 4-1A  (2 remaining games, denom=4)
    # Teams (alphabetical): Coffeeville, French Camp, Leflore County, West Tallahatchie
    # Cutoff: 2025-10-24
    # Actual seeds: Leflore County / West Tallahatchie / Coffeeville / French Camp
    (1, 4): {
        "denom": 4,
        "first_counts":  Counter({'West Tallahatchie': 2, 'Leflore County': 2}),
        "second_counts": Counter({'Leflore County': 2, 'West Tallahatchie': 2}),
        "third_counts":  Counter({'French Camp': 2, 'Coffeeville': 2}),
        "fourth_counts": Counter({'Coffeeville': 2, 'French Camp': 2}),
        "odds": {
        'Coffeeville': StandingsOdds(school='Coffeeville', p1=0.0, p2=0.0, p3=0.5, p4=0.5, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'French Camp': StandingsOdds(school='French Camp', p1=0.0, p2=0.0, p3=0.5, p4=0.5, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Leflore County': StandingsOdds(school='Leflore County', p1=0.5, p2=0.5, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'West Tallahatchie': StandingsOdds(school='West Tallahatchie', p1=0.5, p2=0.5, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        },
    },

    # Region 5-1A  (3 remaining games, denom=8)
    # Teams (alphabetical): Ethel, Leake County, McAdams, Nanih Waiya, Noxapater, Sebastopol
    # Cutoff: 2025-10-24
    # Actual seeds: Nanih Waiya / Leake County / Ethel / Noxapater
    (1, 5): {
        "denom": 8,
        "first_counts":  Counter({'Nanih Waiya': 8.0}),
        "second_counts": Counter({'Leake County': 5.166666666666666, 'Noxapater': 2.8333333333333335}),
        "third_counts":  Counter({'Leake County': 2.8333333333333335, 'Ethel': 2.3333333333333335, 'Noxapater': 2.1666666666666665, 'Sebastopol': 0.6666666666666666}),
        "fourth_counts": Counter({'Noxapater': 3.0, 'Sebastopol': 2.6666666666666665, 'Ethel': 2.333333333333333}),
        "odds": {
        'Ethel': StandingsOdds(school='Ethel', p1=0.0, p2=0.0, p3=0.2916666666666667, p4=0.29166666666666663, p_playoffs=0.5833333333333333, final_playoffs=0.5833333333333333, clinched=False, eliminated=False),
        'Leake County': StandingsOdds(school='Leake County', p1=0.0, p2=0.6458333333333333, p3=0.3541666666666667, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'McAdams': StandingsOdds(school='McAdams', p1=0.0, p2=0.0, p3=0.0, p4=0.0, p_playoffs=0.0, final_playoffs=0.0, clinched=False, eliminated=True),
        'Nanih Waiya': StandingsOdds(school='Nanih Waiya', p1=1.0, p2=0.0, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Noxapater': StandingsOdds(school='Noxapater', p1=0.0, p2=0.3541666666666667, p3=0.2708333333333333, p4=0.375, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Sebastopol': StandingsOdds(school='Sebastopol', p1=0.0, p2=0.0, p3=0.08333333333333333, p4=0.3333333333333333, p_playoffs=0.41666666666666663, final_playoffs=0.41666666666666663, clinched=False, eliminated=False),
        },
    },

    # Region 6-1A  (2 remaining games, denom=4)
    # Teams (alphabetical): Riverside, Shaw, Simmons, South Delta, West Bolivar
    # Cutoff: 2025-10-24
    # Actual seeds: Simmons / South Delta / Shaw / West Bolivar
    (1, 6): {
        "denom": 4,
        "first_counts":  Counter({'Simmons': 4.0}),
        "second_counts": Counter({'South Delta': 4.0}),
        "third_counts":  Counter({'Shaw': 2, 'West Bolivar': 1.9999999999999998}),
        "fourth_counts": Counter({'West Bolivar': 2, 'Riverside': 1.3333333333333333, 'Shaw': 0.6666666666666666}),
        "odds": {
        'Riverside': StandingsOdds(school='Riverside', p1=0.0, p2=0.0, p3=0.0, p4=0.3333333333333333, p_playoffs=0.3333333333333333, final_playoffs=0.3333333333333333, clinched=False, eliminated=False),
        'Shaw': StandingsOdds(school='Shaw', p1=0.0, p2=0.0, p3=0.5, p4=0.16666666666666666, p_playoffs=0.6666666666666666, final_playoffs=0.6666666666666666, clinched=False, eliminated=False),
        'Simmons': StandingsOdds(school='Simmons', p1=1.0, p2=0.0, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'South Delta': StandingsOdds(school='South Delta', p1=0.0, p2=1.0, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'West Bolivar': StandingsOdds(school='West Bolivar', p1=0.0, p2=0.0, p3=0.49999999999999994, p4=0.5, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        },
    },

    # Region 7-1A  (2 remaining games, denom=4)
    # Teams (alphabetical): Bogue Chitto, Mount Olive, Salem, West Lincoln
    # Cutoff: 2025-10-24
    # Actual seeds: Bogue Chitto / Salem / Mount Olive / West Lincoln
    (1, 7): {
        "denom": 4,
        "first_counts":  Counter({'Salem': 2, 'Bogue Chitto': 2}),
        "second_counts": Counter({'Bogue Chitto': 2, 'Salem': 2}),
        "third_counts":  Counter({'West Lincoln': 2, 'Mount Olive': 2}),
        "fourth_counts": Counter({'Mount Olive': 2, 'West Lincoln': 2}),
        "odds": {
        'Bogue Chitto': StandingsOdds(school='Bogue Chitto', p1=0.5, p2=0.5, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Mount Olive': StandingsOdds(school='Mount Olive', p1=0.0, p2=0.0, p3=0.5, p4=0.5, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Salem': StandingsOdds(school='Salem', p1=0.5, p2=0.5, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'West Lincoln': StandingsOdds(school='West Lincoln', p1=0.0, p2=0.0, p3=0.5, p4=0.5, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        },
    },

    # Region 8-1A  (2 remaining games, denom=4)
    # Teams (alphabetical): Lumberton, Resurrection, Richton, Stringer, Taylorsville
    # Cutoff: 2025-10-24
    # Actual seeds: Taylorsville / Stringer / Lumberton / Richton
    (1, 8): {
        "denom": 4,
        "first_counts":  Counter({'Taylorsville': 2.9166666666666665, 'Lumberton': 1.0833333333333333}),
        "second_counts": Counter({'Stringer': 2.9166666666666665, 'Taylorsville': 1.0833333333333333}),
        "third_counts":  Counter({'Lumberton': 2.9166666666666665, 'Stringer': 1.0833333333333333}),
        "fourth_counts": Counter({'Richton': 4.0}),
        "odds": {
        'Lumberton': StandingsOdds(school='Lumberton', p1=0.2708333333333333, p2=0.0, p3=0.7291666666666666, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Resurrection': StandingsOdds(school='Resurrection', p1=0.0, p2=0.0, p3=0.0, p4=0.0, p_playoffs=0.0, final_playoffs=0.0, clinched=False, eliminated=True),
        'Richton': StandingsOdds(school='Richton', p1=0.0, p2=0.0, p3=0.0, p4=1.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Stringer': StandingsOdds(school='Stringer', p1=0.0, p2=0.7291666666666666, p3=0.2708333333333333, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Taylorsville': StandingsOdds(school='Taylorsville', p1=0.7291666666666666, p2=0.2708333333333333, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        },
    },

    # Region 1-2A  (2 remaining games, denom=4)
    # Teams (alphabetical): Baldwyn, Hamilton, Hatley, Walnut
    # Cutoff: 2025-10-24
    # Actual seeds: Baldwyn / Hamilton / Hatley / Walnut
    (2, 1): {
        "denom": 4,
        "first_counts":  Counter({'Baldwyn': 4}),
        "second_counts": Counter({'Hatley': 2, 'Hamilton': 2}),
        "third_counts":  Counter({'Hamilton': 2, 'Hatley': 2}),
        "fourth_counts": Counter({'Walnut': 4}),
        "odds": {
        'Baldwyn': StandingsOdds(school='Baldwyn', p1=1.0, p2=0.0, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Hamilton': StandingsOdds(school='Hamilton', p1=0.0, p2=0.5, p3=0.5, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Hatley': StandingsOdds(school='Hatley', p1=0.0, p2=0.5, p3=0.5, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Walnut': StandingsOdds(school='Walnut', p1=0.0, p2=0.0, p3=0.0, p4=1.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        },
    },

    # Region 2-2A  (2 remaining games, denom=4)
    # Teams (alphabetical): Bruce, East Union, Myrtle, Strayhorn, Water Valley
    # Cutoff: 2025-10-24
    # Actual seeds: Water Valley / Myrtle / Strayhorn / East Union
    (2, 2): {
        "denom": 4,
        "first_counts":  Counter({'Water Valley': 4.0}),
        "second_counts": Counter({'Myrtle': 4.0}),
        "third_counts":  Counter({'Strayhorn': 2.166666666666667, 'East Union': 1.5, 'Bruce': 0.3333333333333333}),
        "fourth_counts": Counter({'East Union': 2.5, 'Bruce': 1.3333333333333333, 'Strayhorn': 0.16666666666666666}),
        "odds": {
        'Bruce': StandingsOdds(school='Bruce', p1=0.0, p2=0.0, p3=0.08333333333333333, p4=0.3333333333333333, p_playoffs=0.41666666666666663, final_playoffs=0.41666666666666663, clinched=False, eliminated=False),
        'East Union': StandingsOdds(school='East Union', p1=0.0, p2=0.0, p3=0.375, p4=0.625, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Myrtle': StandingsOdds(school='Myrtle', p1=0.0, p2=1.0, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Strayhorn': StandingsOdds(school='Strayhorn', p1=0.0, p2=0.0, p3=0.5416666666666667, p4=0.041666666666666664, p_playoffs=0.5833333333333334, final_playoffs=0.5833333333333334, clinched=False, eliminated=False),
        'Water Valley': StandingsOdds(school='Water Valley', p1=1.0, p2=0.0, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        },
    },

    # Region 3-2A  (2 remaining games, denom=4)
    # Teams (alphabetical): Charleston, J Z George, Leland, M. S. Palmer, Northside
    # Cutoff: 2025-10-24
    # Actual seeds: Charleston / Northside / J Z George / Leland
    (2, 3): {
        "denom": 4,
        "first_counts":  Counter({'Charleston': 4}),
        "second_counts": Counter({'Northside': 4}),
        "third_counts":  Counter({'Leland': 2, 'J Z George': 2}),
        "fourth_counts": Counter({'J Z George': 2, 'Leland': 2}),
        "odds": {
        'Charleston': StandingsOdds(school='Charleston', p1=1.0, p2=0.0, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'J Z George': StandingsOdds(school='J Z George', p1=0.0, p2=0.0, p3=0.5, p4=0.5, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Leland': StandingsOdds(school='Leland', p1=0.0, p2=0.0, p3=0.5, p4=0.5, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'M. S. Palmer': StandingsOdds(school='M. S. Palmer', p1=0.0, p2=0.0, p3=0.0, p4=0.0, p_playoffs=0.0, final_playoffs=0.0, clinched=False, eliminated=True),
        'Northside': StandingsOdds(school='Northside', p1=0.0, p2=1.0, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        },
    },

    # Region 4-2A  (2 remaining games, denom=4)
    # Teams (alphabetical): East Webster, Eupora, Kemper County, Philadelphia, Velma Jackson
    # Cutoff: 2025-10-24
    # Actual seeds: East Webster / Kemper County / Velma Jackson / Philadelphia
    (2, 4): {
        "denom": 4,
        "first_counts":  Counter({'East Webster': 4.0}),
        "second_counts": Counter({'Kemper County': 3.0, 'Philadelphia': 1.0}),
        "third_counts":  Counter({'Velma Jackson': 2, 'Philadelphia': 1.0, 'Kemper County': 1.0}),
        "fourth_counts": Counter({'Velma Jackson': 2.0, 'Philadelphia': 2}),
        "odds": {
        'East Webster': StandingsOdds(school='East Webster', p1=1.0, p2=0.0, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Eupora': StandingsOdds(school='Eupora', p1=0.0, p2=0.0, p3=0.0, p4=0.0, p_playoffs=0.0, final_playoffs=0.0, clinched=False, eliminated=True),
        'Kemper County': StandingsOdds(school='Kemper County', p1=0.0, p2=0.75, p3=0.25, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Philadelphia': StandingsOdds(school='Philadelphia', p1=0.0, p2=0.25, p3=0.25, p4=0.5, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Velma Jackson': StandingsOdds(school='Velma Jackson', p1=0.0, p2=0.0, p3=0.5, p4=0.5, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        },
    },

    # Region 5-2A  (2 remaining games, denom=4)
    # Teams (alphabetical): Lake, Newton, Pelahatchie, Puckett, Scott Central
    # Cutoff: 2025-10-24
    # Actual seeds: Scott Central / Lake / Pelahatchie / Newton
    (2, 5): {
        "denom": 4,
        "first_counts":  Counter({'Lake': 2.333333333333333, 'Scott Central': 1.6666666666666665}),
        "second_counts": Counter({'Pelahatchie': 2, 'Lake': 1.6666666666666665, 'Scott Central': 0.3333333333333333}),
        "third_counts":  Counter({'Pelahatchie': 2.0, 'Scott Central': 2}),
        "fourth_counts": Counter({'Newton': 4.0}),
        "odds": {
        'Lake': StandingsOdds(school='Lake', p1=0.5833333333333333, p2=0.41666666666666663, p3=0.0, p4=0.0, p_playoffs=0.9999999999999999, final_playoffs=1.0, clinched=True, eliminated=False),
        'Newton': StandingsOdds(school='Newton', p1=0.0, p2=0.0, p3=0.0, p4=1.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Pelahatchie': StandingsOdds(school='Pelahatchie', p1=0.0, p2=0.5, p3=0.5, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Puckett': StandingsOdds(school='Puckett', p1=0.0, p2=0.0, p3=0.0, p4=0.0, p_playoffs=0.0, final_playoffs=0.0, clinched=False, eliminated=True),
        'Scott Central': StandingsOdds(school='Scott Central', p1=0.41666666666666663, p2=0.08333333333333333, p3=0.5, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        },
    },

    # Region 6-2A  (2 remaining games, denom=4)
    # Teams (alphabetical): Bay Springs, Clarkdale, Enterprise Clarke, Heidelberg, Mize
    # Cutoff: 2025-10-24
    # Actual seeds: Heidelberg / Bay Springs / Mize / Clarkdale
    (2, 6): {
        "denom": 4,
        "first_counts":  Counter({'Heidelberg': 2, 'Clarkdale': 2}),
        "second_counts": Counter({'Heidelberg': 2, 'Bay Springs': 1, 'Clarkdale': 1}),
        "third_counts":  Counter({'Bay Springs': 3, 'Mize': 1}),
        "fourth_counts": Counter({'Enterprise Clarke': 2, 'Clarkdale': 1, 'Mize': 1}),
        "odds": {
        'Bay Springs': StandingsOdds(school='Bay Springs', p1=0.0, p2=0.25, p3=0.75, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Clarkdale': StandingsOdds(school='Clarkdale', p1=0.5, p2=0.25, p3=0.0, p4=0.25, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Enterprise Clarke': StandingsOdds(school='Enterprise Clarke', p1=0.0, p2=0.0, p3=0.0, p4=0.5, p_playoffs=0.5, final_playoffs=0.5, clinched=False, eliminated=False),
        'Heidelberg': StandingsOdds(school='Heidelberg', p1=0.5, p2=0.5, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Mize': StandingsOdds(school='Mize', p1=0.0, p2=0.0, p3=0.25, p4=0.25, p_playoffs=0.5, final_playoffs=0.5, clinched=False, eliminated=False),
        },
    },

    # Region 7-2A  (2 remaining games, denom=4)
    # Teams (alphabetical): Amite County, Enterprise Lincoln, Loyd Star, Wesson, Wilkinson County
    # Cutoff: 2025-10-24
    # Actual seeds: Wesson / Amite County / Loyd Star / Wilkinson County
    (2, 7): {
        "denom": 4,
        "first_counts":  Counter({'Wesson': 4}),
        "second_counts": Counter({'Loyd Star': 2, 'Amite County': 2}),
        "third_counts":  Counter({'Amite County': 2, 'Loyd Star': 2}),
        "fourth_counts": Counter({'Wilkinson County': 2, 'Enterprise Lincoln': 2}),
        "odds": {
        'Amite County': StandingsOdds(school='Amite County', p1=0.0, p2=0.5, p3=0.5, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Enterprise Lincoln': StandingsOdds(school='Enterprise Lincoln', p1=0.0, p2=0.0, p3=0.0, p4=0.5, p_playoffs=0.5, final_playoffs=0.5, clinched=False, eliminated=False),
        'Loyd Star': StandingsOdds(school='Loyd Star', p1=0.0, p2=0.5, p3=0.5, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Wesson': StandingsOdds(school='Wesson', p1=1.0, p2=0.0, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Wilkinson County': StandingsOdds(school='Wilkinson County', p1=0.0, p2=0.0, p3=0.0, p4=0.5, p_playoffs=0.5, final_playoffs=0.5, clinched=False, eliminated=False),
        },
    },

    # Region 8-2A  (2 remaining games, denom=4)
    # Teams (alphabetical): Collins, East Marion, North Forrest, Perry Central, Sacred Heart
    # Cutoff: 2025-10-24
    # Actual seeds: East Marion / North Forrest / Collins / Perry Central
    (2, 8): {
        "denom": 4,
        "first_counts":  Counter({'East Marion': 2, 'North Forrest': 2}),
        "second_counts": Counter({'North Forrest': 2, 'Collins': 2}),
        "third_counts":  Counter({'Collins': 2, 'East Marion': 1, 'Perry Central': 1}),
        "fourth_counts": Counter({'Sacred Heart': 2, 'Perry Central': 1, 'East Marion': 1}),
        "odds": {
        'Collins': StandingsOdds(school='Collins', p1=0.0, p2=0.5, p3=0.5, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'East Marion': StandingsOdds(school='East Marion', p1=0.5, p2=0.0, p3=0.25, p4=0.25, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'North Forrest': StandingsOdds(school='North Forrest', p1=0.5, p2=0.5, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Perry Central': StandingsOdds(school='Perry Central', p1=0.0, p2=0.0, p3=0.25, p4=0.25, p_playoffs=0.5, final_playoffs=0.5, clinched=False, eliminated=False),
        'Sacred Heart': StandingsOdds(school='Sacred Heart', p1=0.0, p2=0.0, p3=0.0, p4=0.5, p_playoffs=0.5, final_playoffs=0.5, clinched=False, eliminated=False),
        },
    },

    # Region 1-3A  (2 remaining games, denom=4)
    # Teams (alphabetical): Alcorn Central, Belmont, Booneville, Kossuth, Mantachie
    # Cutoff: 2025-10-24
    # Actual seeds: Kossuth / Booneville / Belmont / Alcorn Central
    (3, 1): {
        "denom": 4,
        "first_counts":  Counter({'Kossuth': 4.0}),
        "second_counts": Counter({'Booneville': 4.0}),
        "third_counts":  Counter({'Belmont': 2.6666666666666665, 'Alcorn Central': 1, 'Mantachie': 0.3333333333333333}),
        "fourth_counts": Counter({'Alcorn Central': 2, 'Mantachie': 1.6666666666666665, 'Belmont': 0.3333333333333333}),
        "odds": {
        'Alcorn Central': StandingsOdds(school='Alcorn Central', p1=0.0, p2=0.0, p3=0.25, p4=0.5, p_playoffs=0.75, final_playoffs=0.75, clinched=False, eliminated=False),
        'Belmont': StandingsOdds(school='Belmont', p1=0.0, p2=0.0, p3=0.6666666666666666, p4=0.08333333333333333, p_playoffs=0.75, final_playoffs=0.75, clinched=False, eliminated=False),
        'Booneville': StandingsOdds(school='Booneville', p1=0.0, p2=1.0, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Kossuth': StandingsOdds(school='Kossuth', p1=1.0, p2=0.0, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Mantachie': StandingsOdds(school='Mantachie', p1=0.0, p2=0.0, p3=0.08333333333333333, p4=0.41666666666666663, p_playoffs=0.49999999999999994, final_playoffs=0.49999999999999994, clinched=False, eliminated=False),
        },
    },

    # Region 2-3A  (2 remaining games, denom=4)
    # Teams (alphabetical): Coahoma County, Holly Springs, Independence, North Panola
    # Cutoff: 2025-10-24
    # Actual seeds: Coahoma County / North Panola / Independence / Holly Springs
    (3, 2): {
        "denom": 4,
        "first_counts":  Counter({'Coahoma County': 2.6666666666666665, 'Independence': 1.3333333333333333}),
        "second_counts": Counter({'Independence': 1.6666666666666665, 'Coahoma County': 1.3333333333333333, 'North Panola': 1}),
        "third_counts":  Counter({'North Panola': 1.6666666666666665, 'Holly Springs': 1.3333333333333333, 'Independence': 1}),
        "fourth_counts": Counter({'Holly Springs': 2.6666666666666665, 'North Panola': 1.3333333333333333}),
        "odds": {
        'Coahoma County': StandingsOdds(school='Coahoma County', p1=0.6666666666666666, p2=0.3333333333333333, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Holly Springs': StandingsOdds(school='Holly Springs', p1=0.0, p2=0.0, p3=0.3333333333333333, p4=0.6666666666666666, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Independence': StandingsOdds(school='Independence', p1=0.3333333333333333, p2=0.41666666666666663, p3=0.25, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'North Panola': StandingsOdds(school='North Panola', p1=0.0, p2=0.25, p3=0.41666666666666663, p4=0.3333333333333333, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        },
    },

    # Region 3-3A  (2 remaining games, denom=4)
    # Teams (alphabetical): Amanda Elzy, Humphreys County, O'Bannon, Thomas E. Edwards, Yazoo County
    # Cutoff: 2025-10-24
    # Actual seeds: Humphreys County / Thomas E. Edwards / Yazoo County / O'Bannon
    (3, 3): {
        "denom": 4,
        "first_counts":  Counter({'Humphreys County': 4}),
        "second_counts": Counter({'Yazoo County': 2, 'Thomas E. Edwards': 2}),
        "third_counts":  Counter({'Thomas E. Edwards': 2, 'Yazoo County': 2}),
        "fourth_counts": Counter({"O'Bannon": 4}),
        "odds": {
        'Amanda Elzy': StandingsOdds(school='Amanda Elzy', p1=0.0, p2=0.0, p3=0.0, p4=0.0, p_playoffs=0.0, final_playoffs=0.0, clinched=False, eliminated=True),
        'Humphreys County': StandingsOdds(school='Humphreys County', p1=1.0, p2=0.0, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        "O'Bannon": StandingsOdds(school="O'Bannon", p1=0.0, p2=0.0, p3=0.0, p4=1.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Thomas E. Edwards': StandingsOdds(school='Thomas E. Edwards', p1=0.0, p2=0.5, p3=0.5, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Yazoo County': StandingsOdds(school='Yazoo County', p1=0.0, p2=0.5, p3=0.5, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        },
    },

    # Region 4-3A  (2 remaining games, denom=4)
    # Teams (alphabetical): Aberdeen, Choctaw County, Nettleton, Noxubee County, Winona
    # Cutoff: 2025-10-24
    # Actual seeds: Winona / Noxubee County / Choctaw County / Aberdeen
    (3, 4): {
        "denom": 4,
        "first_counts":  Counter({'Aberdeen': 2, 'Winona': 1, 'Noxubee County': 1}),
        "second_counts": Counter({'Winona': 3, 'Noxubee County': 1}),
        "third_counts":  Counter({'Choctaw County': 2, 'Noxubee County': 2}),
        "fourth_counts": Counter({'Aberdeen': 2, 'Choctaw County': 2}),
        "odds": {
        'Aberdeen': StandingsOdds(school='Aberdeen', p1=0.5, p2=0.0, p3=0.0, p4=0.5, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Choctaw County': StandingsOdds(school='Choctaw County', p1=0.0, p2=0.0, p3=0.5, p4=0.5, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Nettleton': StandingsOdds(school='Nettleton', p1=0.0, p2=0.0, p3=0.0, p4=0.0, p_playoffs=0.0, final_playoffs=0.0, clinched=False, eliminated=True),
        'Noxubee County': StandingsOdds(school='Noxubee County', p1=0.25, p2=0.25, p3=0.5, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Winona': StandingsOdds(school='Winona', p1=0.25, p2=0.75, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        },
    },

    # Region 5-3A  (2 remaining games, denom=4)
    # Teams (alphabetical): Pisgah, Quitman, Southeast Lauderdale, St. Andrew's, Union
    # Cutoff: 2025-10-24
    # Actual seeds: Union / Quitman / Southeast Lauderdale / Pisgah
    (3, 5): {
        "denom": 4,
        "first_counts":  Counter({'Union': 4}),
        "second_counts": Counter({'Quitman': 4}),
        "third_counts":  Counter({'Southeast Lauderdale': 4}),
        "fourth_counts": Counter({'Pisgah': 4}),
        "odds": {
        'Pisgah': StandingsOdds(school='Pisgah', p1=0.0, p2=0.0, p3=0.0, p4=1.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Quitman': StandingsOdds(school='Quitman', p1=0.0, p2=1.0, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Southeast Lauderdale': StandingsOdds(school='Southeast Lauderdale', p1=0.0, p2=0.0, p3=1.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        "St. Andrew's": StandingsOdds(school="St. Andrew's", p1=0.0, p2=0.0, p3=0.0, p4=0.0, p_playoffs=0.0, final_playoffs=0.0, clinched=False, eliminated=True),
        'Union': StandingsOdds(school='Union', p1=1.0, p2=0.0, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        },
    },

    # Region 6-3A  (2 remaining games, denom=4)
    # Teams (alphabetical): Jefferson Davis County, Magee, McLaurin, Raleigh, Seminary
    # Cutoff: 2025-10-24
    # Actual seeds: Raleigh / Seminary / Magee / Jefferson Davis County
    (3, 6): {
        "denom": 4,
        "first_counts":  Counter({'Raleigh': 4}),
        "second_counts": Counter({'Seminary': 2, 'Magee': 2}),
        "third_counts":  Counter({'Magee': 2, 'Seminary': 2}),
        "fourth_counts": Counter({'Jefferson Davis County': 4}),
        "odds": {
        'Jefferson Davis County': StandingsOdds(school='Jefferson Davis County', p1=0.0, p2=0.0, p3=0.0, p4=1.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Magee': StandingsOdds(school='Magee', p1=0.0, p2=0.5, p3=0.5, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'McLaurin': StandingsOdds(school='McLaurin', p1=0.0, p2=0.0, p3=0.0, p4=0.0, p_playoffs=0.0, final_playoffs=0.0, clinched=False, eliminated=True),
        'Raleigh': StandingsOdds(school='Raleigh', p1=1.0, p2=0.0, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Seminary': StandingsOdds(school='Seminary', p1=0.0, p2=0.5, p3=0.5, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        },
    },

    # Region 7-3A  (2 remaining games, denom=4)
    # Teams (alphabetical): Crystal Springs, Franklin County, Hazlehurst, Jefferson County, Port Gibson
    # Cutoff: 2025-10-24
    # Actual seeds: Franklin County / Hazlehurst / Jefferson County / Port Gibson
    (3, 7): {
        "denom": 4,
        "first_counts":  Counter({'Franklin County': 2, 'Hazlehurst': 1.0, 'Jefferson County': 1}),
        "second_counts": Counter({'Hazlehurst': 2, 'Franklin County': 1.5833333333333335, 'Jefferson County': 0.4166666666666667}),
        "third_counts":  Counter({'Jefferson County': 2.5833333333333335, 'Hazlehurst': 1, 'Franklin County': 0.4166666666666667}),
        "fourth_counts": Counter({'Port Gibson': 4.0}),
        "odds": {
        'Crystal Springs': StandingsOdds(school='Crystal Springs', p1=0.0, p2=0.0, p3=0.0, p4=0.0, p_playoffs=0.0, final_playoffs=0.0, clinched=False, eliminated=True),
        'Franklin County': StandingsOdds(school='Franklin County', p1=0.5, p2=0.39583333333333337, p3=0.10416666666666667, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Hazlehurst': StandingsOdds(school='Hazlehurst', p1=0.25, p2=0.5, p3=0.25, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Jefferson County': StandingsOdds(school='Jefferson County', p1=0.25, p2=0.10416666666666667, p3=0.6458333333333334, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Port Gibson': StandingsOdds(school='Port Gibson', p1=0.0, p2=0.0, p3=0.0, p4=1.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        },
    },

    # Region 8-3A  (2 remaining games, denom=4)
    # Teams (alphabetical): Presbyterian Christian, St. Patrick, St. Stanislaus, Tylertown, West Marion
    # Cutoff: 2025-10-24
    # Actual seeds: West Marion / Presbyterian Christian / Tylertown / St. Patrick
    (3, 8): {
        "denom": 4,
        "first_counts":  Counter({'West Marion': 4}),
        "second_counts": Counter({'Tylertown': 2, 'Presbyterian Christian': 2}),
        "third_counts":  Counter({'Presbyterian Christian': 2, 'Tylertown': 2}),
        "fourth_counts": Counter({'St. Patrick': 4}),
        "odds": {
        'Presbyterian Christian': StandingsOdds(school='Presbyterian Christian', p1=0.0, p2=0.5, p3=0.5, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'St. Patrick': StandingsOdds(school='St. Patrick', p1=0.0, p2=0.0, p3=0.0, p4=1.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'St. Stanislaus': StandingsOdds(school='St. Stanislaus', p1=0.0, p2=0.0, p3=0.0, p4=0.0, p_playoffs=0.0, final_playoffs=0.0, clinched=False, eliminated=True),
        'Tylertown': StandingsOdds(school='Tylertown', p1=0.0, p2=0.5, p3=0.5, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'West Marion': StandingsOdds(school='West Marion', p1=1.0, p2=0.0, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        },
    },

    # Region 1-4A  (2 remaining games, denom=4)
    # Teams (alphabetical): Corinth, New Albany, North Pontotoc, South Pontotoc, Tishomingo County
    # Cutoff: 2025-10-24
    # Actual seeds: Corinth / North Pontotoc / New Albany / Tishomingo County
    (4, 1): {
        "denom": 4,
        "first_counts":  Counter({'Corinth': 2.5833333333333335, 'New Albany': 1.4166666666666667}),
        "second_counts": Counter({'New Albany': 1.5833333333333335, 'Corinth': 1.4166666666666667, 'North Pontotoc': 1}),
        "third_counts":  Counter({'North Pontotoc': 1.5833333333333335, 'Tishomingo County': 1.4166666666666667, 'New Albany': 1}),
        "fourth_counts": Counter({'Tishomingo County': 2.5833333333333335, 'North Pontotoc': 1.4166666666666667}),
        "odds": {
        'Corinth': StandingsOdds(school='Corinth', p1=0.6458333333333334, p2=0.3541666666666667, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'New Albany': StandingsOdds(school='New Albany', p1=0.3541666666666667, p2=0.39583333333333337, p3=0.25, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'North Pontotoc': StandingsOdds(school='North Pontotoc', p1=0.0, p2=0.25, p3=0.39583333333333337, p4=0.3541666666666667, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'South Pontotoc': StandingsOdds(school='South Pontotoc', p1=0.0, p2=0.0, p3=0.0, p4=0.0, p_playoffs=0.0, final_playoffs=0.0, clinched=False, eliminated=True),
        'Tishomingo County': StandingsOdds(school='Tishomingo County', p1=0.0, p2=0.0, p3=0.3541666666666667, p4=0.6458333333333334, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        },
    },

    # Region 2-4A  (2 remaining games, denom=4)
    # Teams (alphabetical): Amory, Houston, Itawamba Agricultural, Mooreville, Shannon
    # Cutoff: 2025-10-24
    # Actual seeds: Itawamba Agricultural / Shannon / Houston / Amory
    (4, 2): {
        "denom": 4,
        "first_counts":  Counter({'Itawamba Agricultural': 4}),
        "second_counts": Counter({'Shannon': 4}),
        "third_counts":  Counter({'Houston': 4}),
        "fourth_counts": Counter({'Amory': 4}),
        "odds": {
        'Amory': StandingsOdds(school='Amory', p1=0.0, p2=0.0, p3=0.0, p4=1.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Houston': StandingsOdds(school='Houston', p1=0.0, p2=0.0, p3=1.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Itawamba Agricultural': StandingsOdds(school='Itawamba Agricultural', p1=1.0, p2=0.0, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Mooreville': StandingsOdds(school='Mooreville', p1=0.0, p2=0.0, p3=0.0, p4=0.0, p_playoffs=0.0, final_playoffs=0.0, clinched=False, eliminated=True),
        'Shannon': StandingsOdds(school='Shannon', p1=0.0, p2=1.0, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        },
    },

    # Region 3-4A  (2 remaining games, denom=4)
    # Teams (alphabetical): Byhalia, Clarksdale, Ripley, Rosa Fort, Senatobia
    # Cutoff: 2025-10-24
    # Actual seeds: Clarksdale / Senatobia / Rosa Fort / Ripley
    (4, 3): {
        "denom": 4,
        "first_counts":  Counter({'Clarksdale': 2.5, 'Rosa Fort': 1, 'Senatobia': 0.5}),
        "second_counts": Counter({'Senatobia': 2.4166666666666665, 'Clarksdale': 1.3333333333333333, 'Rosa Fort': 0.25}),
        "third_counts":  Counter({'Rosa Fort': 2.75, 'Ripley': 1, 'Clarksdale': 0.16666666666666666, 'Senatobia': 0.08333333333333333}),
        "fourth_counts": Counter({'Ripley': 3.0, 'Senatobia': 1}),
        "odds": {
        'Byhalia': StandingsOdds(school='Byhalia', p1=0.0, p2=0.0, p3=0.0, p4=0.0, p_playoffs=0.0, final_playoffs=0.0, clinched=False, eliminated=True),
        'Clarksdale': StandingsOdds(school='Clarksdale', p1=0.625, p2=0.3333333333333333, p3=0.041666666666666664, p4=0.0, p_playoffs=0.9999999999999999, final_playoffs=1.0, clinched=True, eliminated=False),
        'Ripley': StandingsOdds(school='Ripley', p1=0.0, p2=0.0, p3=0.25, p4=0.75, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Rosa Fort': StandingsOdds(school='Rosa Fort', p1=0.25, p2=0.0625, p3=0.6875, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Senatobia': StandingsOdds(school='Senatobia', p1=0.125, p2=0.6041666666666666, p3=0.020833333333333332, p4=0.25, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        },
    },

    # Region 4-4A  (2 remaining games, denom=4)
    # Teams (alphabetical): Gentry, Greenwood, Kosciusko, Louisville, Yazoo City
    # Cutoff: 2025-10-24
    # Actual seeds: Louisville / Kosciusko / Greenwood / Yazoo City
    (4, 4): {
        "denom": 4,
        "first_counts":  Counter({'Louisville': 2, 'Kosciusko': 1.9999999999999998}),
        "second_counts": Counter({'Kosciusko': 2, 'Louisville': 1.3333333333333333, 'Greenwood': 0.6666666666666666}),
        "third_counts":  Counter({'Greenwood': 3.333333333333333, 'Louisville': 0.6666666666666666}),
        "fourth_counts": Counter({'Yazoo City': 1.9999999999999998, 'Gentry': 1.9999999999999998}),
        "odds": {
        'Gentry': StandingsOdds(school='Gentry', p1=0.0, p2=0.0, p3=0.0, p4=0.49999999999999994, p_playoffs=0.49999999999999994, final_playoffs=0.49999999999999994, clinched=False, eliminated=False),
        'Greenwood': StandingsOdds(school='Greenwood', p1=0.0, p2=0.16666666666666666, p3=0.8333333333333333, p4=0.0, p_playoffs=0.9999999999999999, final_playoffs=1.0, clinched=True, eliminated=False),
        'Kosciusko': StandingsOdds(school='Kosciusko', p1=0.49999999999999994, p2=0.5, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Louisville': StandingsOdds(school='Louisville', p1=0.5, p2=0.3333333333333333, p3=0.16666666666666666, p4=0.0, p_playoffs=0.9999999999999999, final_playoffs=1.0, clinched=True, eliminated=False),
        'Yazoo City': StandingsOdds(school='Yazoo City', p1=0.0, p2=0.0, p3=0.0, p4=0.49999999999999994, p_playoffs=0.49999999999999994, final_playoffs=0.49999999999999994, clinched=False, eliminated=False),
        },
    },

    # Region 5-4A  (2 remaining games, denom=4)
    # Teams (alphabetical): Choctaw Central, Leake Central, Newton County, Northeast Lauderdale, West Lauderdale
    # Cutoff: 2025-10-24
    # Actual seeds: Leake Central / Newton County / West Lauderdale / Choctaw Central
    (4, 5): {
        "denom": 4,
        "first_counts":  Counter({'Leake Central': 4}),
        "second_counts": Counter({'Newton County': 4}),
        "third_counts":  Counter({'West Lauderdale': 2, 'Choctaw Central': 2}),
        "fourth_counts": Counter({'Choctaw Central': 2, 'West Lauderdale': 2}),
        "odds": {
        'Choctaw Central': StandingsOdds(school='Choctaw Central', p1=0.0, p2=0.0, p3=0.5, p4=0.5, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Leake Central': StandingsOdds(school='Leake Central', p1=1.0, p2=0.0, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Newton County': StandingsOdds(school='Newton County', p1=0.0, p2=1.0, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Northeast Lauderdale': StandingsOdds(school='Northeast Lauderdale', p1=0.0, p2=0.0, p3=0.0, p4=0.0, p_playoffs=0.0, final_playoffs=0.0, clinched=False, eliminated=True),
        'West Lauderdale': StandingsOdds(school='West Lauderdale', p1=0.0, p2=0.0, p3=0.5, p4=0.5, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        },
    },

    # Region 6-4A  (2 remaining games, denom=4)
    # Teams (alphabetical): Forest, Mendenhall, Morton, Raymond, Richland
    # Cutoff: 2025-10-24
    # Actual seeds: Forest / Morton / Mendenhall / Richland
    (4, 6): {
        "denom": 4,
        "first_counts":  Counter({'Morton': 2, 'Forest': 2}),
        "second_counts": Counter({'Forest': 2, 'Morton': 2}),
        "third_counts":  Counter({'Mendenhall': 4}),
        "fourth_counts": Counter({'Richland': 4}),
        "odds": {
        'Forest': StandingsOdds(school='Forest', p1=0.5, p2=0.5, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Mendenhall': StandingsOdds(school='Mendenhall', p1=0.0, p2=0.0, p3=1.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Morton': StandingsOdds(school='Morton', p1=0.5, p2=0.5, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Raymond': StandingsOdds(school='Raymond', p1=0.0, p2=0.0, p3=0.0, p4=0.0, p_playoffs=0.0, final_playoffs=0.0, clinched=False, eliminated=True),
        'Richland': StandingsOdds(school='Richland', p1=0.0, p2=0.0, p3=0.0, p4=1.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        },
    },

    # Region 7-4A  (2 remaining games, denom=4)
    # Teams (alphabetical): Columbia, Lawrence County, McComb, Poplarville, South Pike
    # Cutoff: 2025-10-24
    # Actual seeds: Columbia / McComb / Poplarville / South Pike
    (4, 7): {
        "denom": 4,
        "first_counts":  Counter({'Columbia': 2.5, 'Poplarville': 1.5}),
        "second_counts": Counter({'Columbia': 1.5, 'Poplarville': 1.5, 'McComb': 1}),
        "third_counts":  Counter({'South Pike': 1.5, 'McComb': 1.5, 'Poplarville': 1}),
        "fourth_counts": Counter({'South Pike': 2.5, 'McComb': 1.5}),
        "odds": {
        'Columbia': StandingsOdds(school='Columbia', p1=0.625, p2=0.375, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Lawrence County': StandingsOdds(school='Lawrence County', p1=0.0, p2=0.0, p3=0.0, p4=0.0, p_playoffs=0.0, final_playoffs=0.0, clinched=False, eliminated=True),
        'McComb': StandingsOdds(school='McComb', p1=0.0, p2=0.25, p3=0.375, p4=0.375, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Poplarville': StandingsOdds(school='Poplarville', p1=0.375, p2=0.375, p3=0.25, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'South Pike': StandingsOdds(school='South Pike', p1=0.0, p2=0.0, p3=0.375, p4=0.625, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        },
    },

    # Region 8-4A  (2 remaining games, denom=4)
    # Teams (alphabetical): Bay, Forrest County Agricultural, Greene County, Moss Point, Pass Christian
    # Cutoff: 2025-10-24
    # Actual seeds: Pass Christian / Forrest County Agricultural / Greene County / Moss Point
    (4, 8): {
        "denom": 4,
        "first_counts":  Counter({'Pass Christian': 4}),
        "second_counts": Counter({'Greene County': 2, 'Forrest County Agricultural': 2}),
        "third_counts":  Counter({'Forrest County Agricultural': 2, 'Greene County': 2}),
        "fourth_counts": Counter({'Moss Point': 4}),
        "odds": {
        'Bay': StandingsOdds(school='Bay', p1=0.0, p2=0.0, p3=0.0, p4=0.0, p_playoffs=0.0, final_playoffs=0.0, clinched=False, eliminated=True),
        'Forrest County Agricultural': StandingsOdds(school='Forrest County Agricultural', p1=0.0, p2=0.5, p3=0.5, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Greene County': StandingsOdds(school='Greene County', p1=0.0, p2=0.5, p3=0.5, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Moss Point': StandingsOdds(school='Moss Point', p1=0.0, p2=0.0, p3=0.0, p4=1.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Pass Christian': StandingsOdds(school='Pass Christian', p1=1.0, p2=0.0, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        },
    },

    # Region 1-5A  (3 remaining games, denom=8)
    # Teams (alphabetical): Caledonia, Columbus, Lafayette, New Hope, Pontotoc, West Point
    # Cutoff: 2025-10-31
    # Actual seeds: West Point / New Hope / Pontotoc / Lafayette
    (5, 1): {
        "denom": 8,
        "first_counts":  Counter({'West Point': 8}),
        "second_counts": Counter({'New Hope': 8}),
        "third_counts":  Counter({'Pontotoc': 4, 'Lafayette': 4}),
        "fourth_counts": Counter({'Lafayette': 4, 'Pontotoc': 4}),
        "odds": {
        'Caledonia': StandingsOdds(school='Caledonia', p1=0.0, p2=0.0, p3=0.0, p4=0.0, p_playoffs=0.0, final_playoffs=0.0, clinched=False, eliminated=True),
        'Columbus': StandingsOdds(school='Columbus', p1=0.0, p2=0.0, p3=0.0, p4=0.0, p_playoffs=0.0, final_playoffs=0.0, clinched=False, eliminated=True),
        'Lafayette': StandingsOdds(school='Lafayette', p1=0.0, p2=0.0, p3=0.5, p4=0.5, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'New Hope': StandingsOdds(school='New Hope', p1=0.0, p2=1.0, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Pontotoc': StandingsOdds(school='Pontotoc', p1=0.0, p2=0.0, p3=0.5, p4=0.5, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'West Point': StandingsOdds(school='West Point', p1=1.0, p2=0.0, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        },
    },

    # Region 2-5A  (3 remaining games, denom=8)
    # Teams (alphabetical): Cleveland Central, Florence, Holmes County Central, Lanier, Provine, Vicksburg
    # Cutoff: 2025-10-31
    # Actual seeds: Cleveland Central / Lanier / Holmes County Central / Vicksburg
    (5, 2): {
        "denom": 8,
        "first_counts":  Counter({'Cleveland Central': 6.0, 'Lanier': 2}),
        "second_counts": Counter({'Lanier': 3.4166666666666665, 'Vicksburg': 2.583333333333333, 'Cleveland Central': 1, 'Florence': 1}),
        "third_counts":  Counter({'Lanier': 2.583333333333333, 'Holmes County Central': 2, 'Vicksburg': 1.4166666666666665, 'Cleveland Central': 1, 'Florence': 1}),
        "fourth_counts": Counter({'Holmes County Central': 4.0, 'Florence': 2, 'Vicksburg': 2}),
        "odds": {
        'Cleveland Central': StandingsOdds(school='Cleveland Central', p1=0.75, p2=0.125, p3=0.125, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Florence': StandingsOdds(school='Florence', p1=0.0, p2=0.125, p3=0.125, p4=0.25, p_playoffs=0.5, final_playoffs=0.5, clinched=False, eliminated=False),
        'Holmes County Central': StandingsOdds(school='Holmes County Central', p1=0.0, p2=0.0, p3=0.25, p4=0.5, p_playoffs=0.75, final_playoffs=0.75, clinched=False, eliminated=False),
        'Lanier': StandingsOdds(school='Lanier', p1=0.25, p2=0.4270833333333333, p3=0.32291666666666663, p4=0.0, p_playoffs=0.9999999999999999, final_playoffs=1.0, clinched=True, eliminated=False),
        'Provine': StandingsOdds(school='Provine', p1=0.0, p2=0.0, p3=0.0, p4=0.0, p_playoffs=0.0, final_playoffs=0.0, clinched=False, eliminated=True),
        'Vicksburg': StandingsOdds(school='Vicksburg', p1=0.0, p2=0.32291666666666663, p3=0.17708333333333331, p4=0.25, p_playoffs=0.75, final_playoffs=0.75, clinched=False, eliminated=False),
        },
    },

    # Region 3-5A  (3 remaining games, denom=8)
    # Teams (alphabetical): Brookhaven, Laurel, Natchez, North Pike, South Jones, Sumrall
    # Cutoff: 2025-10-31
    # Actual seeds: Brookhaven / Laurel / South Jones / Sumrall
    (5, 3): {
        "denom": 8,
        "first_counts":  Counter({'Brookhaven': 8}),
        "second_counts": Counter({'South Jones': 4, 'Laurel': 4}),
        "third_counts":  Counter({'Laurel': 4, 'South Jones': 2, 'Natchez': 1, 'North Pike': 1}),
        "fourth_counts": Counter({'Sumrall': 4, 'North Pike': 2, 'Natchez': 1, 'South Jones': 1}),
        "odds": {
        'Brookhaven': StandingsOdds(school='Brookhaven', p1=1.0, p2=0.0, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Laurel': StandingsOdds(school='Laurel', p1=0.0, p2=0.5, p3=0.5, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Natchez': StandingsOdds(school='Natchez', p1=0.0, p2=0.0, p3=0.125, p4=0.125, p_playoffs=0.25, final_playoffs=0.25, clinched=False, eliminated=False),
        'North Pike': StandingsOdds(school='North Pike', p1=0.0, p2=0.0, p3=0.125, p4=0.25, p_playoffs=0.375, final_playoffs=0.375, clinched=False, eliminated=False),
        'South Jones': StandingsOdds(school='South Jones', p1=0.0, p2=0.5, p3=0.25, p4=0.125, p_playoffs=0.875, final_playoffs=0.875, clinched=False, eliminated=False),
        'Sumrall': StandingsOdds(school='Sumrall', p1=0.0, p2=0.0, p3=0.0, p4=0.5, p_playoffs=0.5, final_playoffs=0.5, clinched=False, eliminated=False),
        },
    },

    # Region 4-5A  (3 remaining games, denom=8)
    # Teams (alphabetical): East Central, Northeast Jones, Purvis, Stone, Vancleave, Wayne County
    # Cutoff: 2025-10-31
    # Actual seeds: Stone / Wayne County / Purvis / Northeast Jones
    (5, 4): {
        "denom": 8,
        "first_counts":  Counter({'Stone': 8}),
        "second_counts": Counter({'Wayne County': 8}),
        "third_counts":  Counter({'Purvis': 4, 'Vancleave': 3, 'East Central': 1}),
        "fourth_counts": Counter({'Purvis': 3, 'Northeast Jones': 3, 'Vancleave': 1, 'East Central': 1}),
        "odds": {
        'East Central': StandingsOdds(school='East Central', p1=0.0, p2=0.0, p3=0.125, p4=0.125, p_playoffs=0.25, final_playoffs=0.25, clinched=False, eliminated=False),
        'Northeast Jones': StandingsOdds(school='Northeast Jones', p1=0.0, p2=0.0, p3=0.0, p4=0.375, p_playoffs=0.375, final_playoffs=0.375, clinched=False, eliminated=False),
        'Purvis': StandingsOdds(school='Purvis', p1=0.0, p2=0.0, p3=0.5, p4=0.375, p_playoffs=0.875, final_playoffs=0.875, clinched=False, eliminated=False),
        'Stone': StandingsOdds(school='Stone', p1=1.0, p2=0.0, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Vancleave': StandingsOdds(school='Vancleave', p1=0.0, p2=0.0, p3=0.375, p4=0.125, p_playoffs=0.5, final_playoffs=0.5, clinched=False, eliminated=False),
        'Wayne County': StandingsOdds(school='Wayne County', p1=0.0, p2=1.0, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        },
    },

    # Region 1-6A  (3 remaining games, denom=8)
    # Teams (alphabetical): Center Hill, Grenada, Lake Cormorant, Olive Branch, Saltillo, South Panola
    # Cutoff: 2025-10-31
    # Actual seeds: South Panola / Lake Cormorant / Grenada / Center Hill
    (6, 1): {
        "denom": 8,
        "first_counts":  Counter({'South Panola': 8}),
        "second_counts": Counter({'Lake Cormorant': 8}),
        "third_counts":  Counter({'Grenada': 6, 'Center Hill': 2}),
        "fourth_counts": Counter({'Center Hill': 6, 'Saltillo': 2}),
        "odds": {
        'Center Hill': StandingsOdds(school='Center Hill', p1=0.0, p2=0.0, p3=0.25, p4=0.75, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Grenada': StandingsOdds(school='Grenada', p1=0.0, p2=0.0, p3=0.75, p4=0.0, p_playoffs=0.75, final_playoffs=0.75, clinched=False, eliminated=False),
        'Lake Cormorant': StandingsOdds(school='Lake Cormorant', p1=0.0, p2=1.0, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Olive Branch': StandingsOdds(school='Olive Branch', p1=0.0, p2=0.0, p3=0.0, p4=0.0, p_playoffs=0.0, final_playoffs=0.0, clinched=False, eliminated=True),
        'Saltillo': StandingsOdds(school='Saltillo', p1=0.0, p2=0.0, p3=0.0, p4=0.25, p_playoffs=0.25, final_playoffs=0.25, clinched=False, eliminated=False),
        'South Panola': StandingsOdds(school='South Panola', p1=1.0, p2=0.0, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        },
    },

    # Region 2-6A  (3 remaining games, denom=8)
    # Teams (alphabetical): Callaway, Canton, Greenville, Neshoba Central, Ridgeland, Warren Central
    # Cutoff: 2025-10-31
    # Actual seeds: Warren Central / Ridgeland / Callaway / Neshoba Central
    (6, 2): {
        "denom": 8,
        "first_counts":  Counter({'Warren Central': 8}),
        "second_counts": Counter({'Ridgeland': 8}),
        "third_counts":  Counter({'Neshoba Central': 4, 'Callaway': 4}),
        "fourth_counts": Counter({'Callaway': 4, 'Neshoba Central': 4}),
        "odds": {
        'Callaway': StandingsOdds(school='Callaway', p1=0.0, p2=0.0, p3=0.5, p4=0.5, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Canton': StandingsOdds(school='Canton', p1=0.0, p2=0.0, p3=0.0, p4=0.0, p_playoffs=0.0, final_playoffs=0.0, clinched=False, eliminated=True),
        'Greenville': StandingsOdds(school='Greenville', p1=0.0, p2=0.0, p3=0.0, p4=0.0, p_playoffs=0.0, final_playoffs=0.0, clinched=False, eliminated=True),
        'Neshoba Central': StandingsOdds(school='Neshoba Central', p1=0.0, p2=0.0, p3=0.5, p4=0.5, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Ridgeland': StandingsOdds(school='Ridgeland', p1=0.0, p2=1.0, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Warren Central': StandingsOdds(school='Warren Central', p1=1.0, p2=0.0, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        },
    },

    # Region 3-6A  (3 remaining games, denom=8)
    # Teams (alphabetical): Forest Hill, George County, Hattiesburg, Jim Hill, Terry, West Jones
    # Cutoff: 2025-10-31
    # Actual seeds: Hattiesburg / West Jones / Terry / George County
    (6, 3): {
        "denom": 8,
        "first_counts":  Counter({'Hattiesburg': 5.666666666666667, 'Terry': 2.3333333333333335}),
        "second_counts": Counter({'West Jones': 5.0, 'Hattiesburg': 2.3333333333333335, 'Terry': 0.6666666666666667}),
        "third_counts":  Counter({'Terry': 5.0, 'West Jones': 3.0}),
        "fourth_counts": Counter({'George County': 5.333333333333333, 'Jim Hill': 2, 'Forest Hill': 0.6666666666666667}),
        "odds": {
        'Forest Hill': StandingsOdds(school='Forest Hill', p1=0.0, p2=0.0, p3=0.0, p4=0.08333333333333334, p_playoffs=0.08333333333333334, final_playoffs=0.08333333333333334, clinched=False, eliminated=False),
        'George County': StandingsOdds(school='George County', p1=0.0, p2=0.0, p3=0.0, p4=0.6666666666666666, p_playoffs=0.6666666666666666, final_playoffs=0.6666666666666666, clinched=False, eliminated=False),
        'Hattiesburg': StandingsOdds(school='Hattiesburg', p1=0.7083333333333334, p2=0.2916666666666667, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Jim Hill': StandingsOdds(school='Jim Hill', p1=0.0, p2=0.0, p3=0.0, p4=0.25, p_playoffs=0.25, final_playoffs=0.25, clinched=False, eliminated=False),
        'Terry': StandingsOdds(school='Terry', p1=0.2916666666666667, p2=0.08333333333333334, p3=0.625, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'West Jones': StandingsOdds(school='West Jones', p1=0.0, p2=0.625, p3=0.375, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        },
    },

    # Region 4-6A  (3 remaining games, denom=8)
    # Teams (alphabetical): Gautier, Hancock, Long Beach, Pascagoula, Pearl River Central, Picayune
    # Cutoff: 2025-10-31
    # Actual seeds: Picayune / Pascagoula / Hancock / Pearl River Central
    (6, 4): {
        "denom": 8,
        "first_counts":  Counter({'Picayune': 8}),
        "second_counts": Counter({'Pascagoula': 8}),
        "third_counts":  Counter({'Hancock': 6, 'Pearl River Central': 2}),
        "fourth_counts": Counter({'Pearl River Central': 6, 'Hancock': 2}),
        "odds": {
        'Gautier': StandingsOdds(school='Gautier', p1=0.0, p2=0.0, p3=0.0, p4=0.0, p_playoffs=0.0, final_playoffs=0.0, clinched=False, eliminated=True),
        'Hancock': StandingsOdds(school='Hancock', p1=0.0, p2=0.0, p3=0.75, p4=0.25, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Long Beach': StandingsOdds(school='Long Beach', p1=0.0, p2=0.0, p3=0.0, p4=0.0, p_playoffs=0.0, final_playoffs=0.0, clinched=False, eliminated=True),
        'Pascagoula': StandingsOdds(school='Pascagoula', p1=0.0, p2=1.0, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Pearl River Central': StandingsOdds(school='Pearl River Central', p1=0.0, p2=0.0, p3=0.25, p4=0.75, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Picayune': StandingsOdds(school='Picayune', p1=1.0, p2=0.0, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        },
    },

    # Region 1-7A  (3 remaining games, denom=8)
    # Teams (alphabetical): Desoto Central, Hernando, Horn Lake, Lewisburg, Southaven, Tupelo
    # Cutoff: 2025-10-31
    # Actual seeds: Tupelo / Horn Lake / Desoto Central / Hernando
    (7, 1): {
        "denom": 8,
        "first_counts":  Counter({'Tupelo': 4, 'Desoto Central': 4}),
        "second_counts": Counter({'Tupelo': 4, 'Desoto Central': 2, 'Horn Lake': 2}),
        "third_counts":  Counter({'Horn Lake': 3, 'Hernando': 3, 'Desoto Central': 2}),
        "fourth_counts": Counter({'Southaven': 4, 'Horn Lake': 3, 'Hernando': 1}),
        "odds": {
        'Desoto Central': StandingsOdds(school='Desoto Central', p1=0.5, p2=0.25, p3=0.25, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Hernando': StandingsOdds(school='Hernando', p1=0.0, p2=0.0, p3=0.375, p4=0.125, p_playoffs=0.5, final_playoffs=0.5, clinched=False, eliminated=False),
        'Horn Lake': StandingsOdds(school='Horn Lake', p1=0.0, p2=0.25, p3=0.375, p4=0.375, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Lewisburg': StandingsOdds(school='Lewisburg', p1=0.0, p2=0.0, p3=0.0, p4=0.0, p_playoffs=0.0, final_playoffs=0.0, clinched=False, eliminated=True),
        'Southaven': StandingsOdds(school='Southaven', p1=0.0, p2=0.0, p3=0.0, p4=0.5, p_playoffs=0.5, final_playoffs=0.5, clinched=False, eliminated=False),
        'Tupelo': StandingsOdds(school='Tupelo', p1=0.5, p2=0.5, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        },
    },

    # Region 2-7A  (3 remaining games, denom=8)
    # Teams (alphabetical): Clinton, Germantown, Madison Central, Murrah, Oxford, Starkville
    # Cutoff: 2025-10-31
    # Actual seeds: Oxford / Germantown / Madison Central / Starkville
    (7, 2): {
        "denom": 8,
        "first_counts":  Counter({'Oxford': 8.0}),
        "second_counts": Counter({'Germantown': 8.0}),
        "third_counts":  Counter({'Madison Central': 4, 'Starkville': 4.0}),
        "fourth_counts": Counter({'Starkville': 4, 'Clinton': 2.833333333333333, 'Madison Central': 1.1666666666666667}),
        "odds": {
        'Clinton': StandingsOdds(school='Clinton', p1=0.0, p2=0.0, p3=0.0, p4=0.35416666666666663, p_playoffs=0.35416666666666663, final_playoffs=0.35416666666666663, clinched=False, eliminated=False),
        'Germantown': StandingsOdds(school='Germantown', p1=0.0, p2=1.0, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Madison Central': StandingsOdds(school='Madison Central', p1=0.0, p2=0.0, p3=0.5, p4=0.14583333333333334, p_playoffs=0.6458333333333334, final_playoffs=0.6458333333333334, clinched=False, eliminated=False),
        'Murrah': StandingsOdds(school='Murrah', p1=0.0, p2=0.0, p3=0.0, p4=0.0, p_playoffs=0.0, final_playoffs=0.0, clinched=False, eliminated=True),
        'Oxford': StandingsOdds(school='Oxford', p1=1.0, p2=0.0, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Starkville': StandingsOdds(school='Starkville', p1=0.0, p2=0.0, p3=0.5, p4=0.5, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        },
    },

    # Region 3-7A  (3 remaining games, denom=8)
    # Teams (alphabetical): Brandon, Meridian, Northwest Rankin, Oak Grove, Pearl, Petal
    # Cutoff: 2025-10-31
    # Actual seeds: Oak Grove / Petal / Brandon / Northwest Rankin
    (7, 3): {
        "denom": 8,
        "first_counts":  Counter({'Petal': 4.104166666666667, 'Oak Grove': 2.375, 'Northwest Rankin': 1.1874999999999998, 'Pearl': 0.33333333333333337}),
        "second_counts": Counter({'Pearl': 3.2500000000000004, 'Oak Grove': 2.0416666666666665, 'Northwest Rankin': 1.5624999999999998, 'Petal': 1.1458333333333333}),
        "third_counts":  Counter({'Brandon': 3, 'Petal': 2.4861111111111125, 'Oak Grove': 2.243055555555556, 'Northwest Rankin': 0.14583333333333334, 'Pearl': 0.125}),
        "fourth_counts": Counter({'Northwest Rankin': 3.1041666666666665, 'Brandon': 3, 'Oak Grove': 1.3402777777777775, 'Pearl': 0.29166666666666674, 'Petal': 0.2638888888888889}),
        "odds": {
        'Brandon': StandingsOdds(school='Brandon', p1=0.0, p2=0.0, p3=0.375, p4=0.375, p_playoffs=0.75, final_playoffs=0.75, clinched=False, eliminated=False),
        'Meridian': StandingsOdds(school='Meridian', p1=0.0, p2=0.0, p3=0.0, p4=0.0, p_playoffs=0.0, final_playoffs=0.0, clinched=False, eliminated=True),
        'Northwest Rankin': StandingsOdds(school='Northwest Rankin', p1=0.14843749999999997, p2=0.19531249999999997, p3=0.018229166666666668, p4=0.3880208333333333, p_playoffs=0.75, final_playoffs=0.75, clinched=False, eliminated=False),
        'Oak Grove': StandingsOdds(school='Oak Grove', p1=0.296875, p2=0.2552083333333333, p3=0.2803819444444445, p4=0.16753472222222218, p_playoffs=0.9999999999999999, final_playoffs=1.0, clinched=True, eliminated=False),
        'Pearl': StandingsOdds(school='Pearl', p1=0.04166666666666667, p2=0.40625000000000006, p3=0.015625, p4=0.03645833333333334, p_playoffs=0.5000000000000001, final_playoffs=0.5000000000000001, clinched=False, eliminated=False),
        'Petal': StandingsOdds(school='Petal', p1=0.5130208333333334, p2=0.14322916666666666, p3=0.31076388888888906, p4=0.03298611111111111, p_playoffs=1.0000000000000002, final_playoffs=1.0, clinched=True, eliminated=False),
        },
    },

    # Region 4-7A  (3 remaining games, denom=8)
    # Teams (alphabetical): Biloxi, D'Iberville, Gulfport, Harrison Central, Ocean Springs, St. Martin, West Harrison
    # Cutoff: 2025-10-31
    # Actual seeds: Gulfport / Ocean Springs / D'Iberville / Biloxi
    (7, 4): {
        "denom": 8,
        "first_counts":  Counter({'Gulfport': 8}),
        "second_counts": Counter({'Ocean Springs': 8}),
        "third_counts":  Counter({"D'Iberville": 4, 'St. Martin': 2, 'Biloxi': 2}),
        "fourth_counts": Counter({'Biloxi': 4, 'St. Martin': 2, "D'Iberville": 2}),
        "odds": {
        'Biloxi': StandingsOdds(school='Biloxi', p1=0.0, p2=0.0, p3=0.25, p4=0.5, p_playoffs=0.75, final_playoffs=0.75, clinched=False, eliminated=False),
        "D'Iberville": StandingsOdds(school="D'Iberville", p1=0.0, p2=0.0, p3=0.5, p4=0.25, p_playoffs=0.75, final_playoffs=0.75, clinched=False, eliminated=False),
        'Gulfport': StandingsOdds(school='Gulfport', p1=1.0, p2=0.0, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'Harrison Central': StandingsOdds(school='Harrison Central', p1=0.0, p2=0.0, p3=0.0, p4=0.0, p_playoffs=0.0, final_playoffs=0.0, clinched=False, eliminated=True),
        'Ocean Springs': StandingsOdds(school='Ocean Springs', p1=0.0, p2=1.0, p3=0.0, p4=0.0, p_playoffs=1.0, final_playoffs=1.0, clinched=True, eliminated=False),
        'St. Martin': StandingsOdds(school='St. Martin', p1=0.0, p2=0.0, p3=0.25, p4=0.25, p_playoffs=0.5, final_playoffs=0.5, clinched=False, eliminated=False),
        'West Harrison': StandingsOdds(school='West Harrison', p1=0.0, p2=0.0, p3=0.0, p4=0.0, p_playoffs=0.0, final_playoffs=0.0, clinched=False, eliminated=True),
        },
    },

}
