x-env-common: &env-common
  ENVIRONMENT: "${ENVIRONMENT:-local}"
  NETWORK: "${NETWORK:-mshsfootball-local}"
  PREFECT_API_URL: "${PREFECT_API_URL:-http://prefect-server:4200/api}"
  PREFECT_LOGGING_LEVEL: "${PREFECT_LOGGING_LEVEL:-INFO}"
  POSTGRES_HOST: "${POSTGRES_HOST:-db}"
  POSTGRES_PORT: "${POSTGRES_PORT:-5432}"
  POSTGRES_DB: "${POSTGRES_DB:-mshsfootball}"
  POSTGRES_USER: "${POSTGRES_USER:-postgres}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-postgres}"
  PREFECT_PORT: "${PREFECT_PORT:-4200}"
  PREFECT_VERSION: "${PREFECT_VERSION:-2.17.1}"
  PYTHON_VERSION: "${PYTHON_VERSION:-3.11}"
  POSTGRES_VERSION: "${POSTGRES_VERSION:-17}"

services:
  prefect-server:
    image: prefecthq/prefect:${PREFECT_VERSION}-python${PYTHON_VERSION}
    container_name: prefect-server_${ENVIRONMENT}
    ports:
      - "${PREFECT_PORT}:4200"
    restart: unless-stopped
    command: prefect server start --host 0.0.0.0 --port ${PREFECT_PORT}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      <<: *env-common
    networks:
      - mshsfootball
    volumes:
      - prefect-data:/root/.prefect

  prefect-worker:
    build:
      context: .
      dockerfile: prefect/Dockerfile.prefect
      args:
        - ENVIRONMENT=${ENVIRONMENT}
        - PREFECT_VERSION=${PREFECT_VERSION}
        - PYTHON_VERSION=${PYTHON_VERSION}
    container_name: prefect-worker_${ENVIRONMENT}
    restart: unless-stopped
    environment:
      <<: *env-common
    networks:
      - mshsfootball
    depends_on:
      - prefect-server

  # Local PostgreSQL for testing (disabled on VM by using profiles)
  db:
    image: postgres:${POSTGRES_VERSION:-17}
    profiles: ["local-db"]
    environment:
      <<: *env-common
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - mshsfootball
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER:-postgres}"]
      interval: 5s
      timeout: 3s
      retries: 20

networks:
  mshsfootball:
    name: mshsfootball_${ENVIRONMENT}
    driver: bridge

volumes:
  dbdata:
    driver: local
  prefect-data:
    driver: local
