"""Generate pre-final-week fixture data for target regions.

Prints Python source code for a fixture dict mapping (class, region) to
expected scenario counts and odds at the one-week-out cutoff.

Run from repo root:
    source .venv/bin/activate
    python backend/scripts/gen_pre_final_week_fixtures.py
"""

import sys
from collections import Counter, defaultdict

sys.path.insert(0, ".")

from backend.helpers.data_classes import RemainingGame
from backend.helpers.data_helpers import get_completed_games
from backend.helpers.scenarios import determine_odds, determine_scenarios
from backend.tests.data.results_2025_ground_truth import (
    REGION_RESULTS_2025,
    expand_results,
    teams_from_games,
)

TARGETS = sorted(REGION_RESULTS_2025.keys())

CUTOFFS = {
    1: "2025-10-24",
    2: "2025-10-24",
    3: "2025-10-24",
    4: "2025-10-24",
    5: "2025-10-31",
    6: "2025-10-31",
    7: "2025-10-31",
}


def split_games(fixture, clazz):
    """Split a RegionFixture's games into completed and remaining based on the class cutoff.

    Args:
        fixture: A RegionFixture dict from REGION_RESULTS_2025.
        clazz: Integer class (1–7); determines the cutoff date.

    Returns:
        Tuple of (completed_raw list of RawCompletedGame dicts, list of RemainingGame).
    """
    cutoff = CUTOFFS[clazz]
    all_games = fixture["games"]
    completed_compact = [g for g in all_games if g["date"] <= cutoff]
    remaining_compact = [g for g in all_games if g["date"] > cutoff]
    completed_raw = expand_results(completed_compact)
    remaining_games = [RemainingGame(*sorted([g["winner"], g["loser"]])) for g in remaining_compact]
    return completed_raw, remaining_games


def counter_repr(c: Counter | defaultdict) -> str:
    """Return a ``Counter({...})`` literal string sorted by descending value.

    Args:
        c: Counter whose keys are team name strings and values are scenario counts.

    Returns:
        Python source string suitable for embedding in a generated fixture file.
    """
    items = ", ".join(f"{k!r}: {v}" for k, v in sorted(c.items(), key=lambda x: -x[1]))
    return f"Counter({{{items}}})"


def odds_repr(school, o) -> str:
    """Return a ``'school': StandingsOdds(...)`` line for a generated fixture file.

    Args:
        school: Team name string used as the dict key.
        o: StandingsOdds instance whose fields are serialized as keyword arguments.

    Returns:
        Indented Python source string ending with a trailing comma.
    """
    return (
        f"        {school!r}: StandingsOdds("
        f"school={o.school!r}, "
        f"p1={o.p1!r}, "
        f"p2={o.p2!r}, "
        f"p3={o.p3!r}, "
        f"p4={o.p4!r}, "
        f"p_playoffs={o.p_playoffs!r}, "
        f"final_playoffs={o.final_playoffs!r}, "
        f"clinched={o.clinched!r}, "
        f"eliminated={o.eliminated!r}"
        f"),"
    )


print('"""Pre-computed expected counts and odds for target regions at the pre-final-week cutoff.')
print("")
print("Generated by backend/scripts/gen_pre_final_week_fixtures.py from 2025 season data.")
print("Cutoffs: 1A–4A on or before 2025-10-24; 5A–7A on or before 2025-10-31.")
print('"""')
print("")
print("from collections import Counter")
print("")
print("from backend.helpers.data_classes import StandingsOdds")
print("")
print("PRE_FINAL_WEEK_EXPECTED: dict[tuple[int, int], dict] = {")

for clazz, region in TARGETS:
    key = (clazz, region)
    fixture = REGION_RESULTS_2025[key]
    completed_raw, remaining_games = split_games(fixture, clazz)
    teams = teams_from_games(fixture["games"])
    completed = get_completed_games(completed_raw)

    r = determine_scenarios(teams, completed, remaining_games)
    odds = determine_odds(
        teams,
        r.first_counts,
        r.second_counts,
        r.third_counts,
        r.fourth_counts,
        r.denom,
    )

    denom = int(r.denom)
    remaining_count = len(remaining_games)

    print(f"    # Region {region}-{clazz}A  ({remaining_count} remaining games, denom={denom})")
    print(f"    # Teams (alphabetical): {', '.join(teams)}")
    print(f"    # Cutoff: {CUTOFFS[clazz]}")
    seeds = fixture["seeds"]
    print(f"    # Actual seeds: {seeds[1]} / {seeds[2]} / {seeds[3]} / {seeds[4]}")
    print(f"    ({clazz}, {region}): {{")
    print(f'        "denom": {denom},')
    print(f'        "first_counts":  {counter_repr(r.first_counts)},')
    print(f'        "second_counts": {counter_repr(r.second_counts)},')
    print(f'        "third_counts":  {counter_repr(r.third_counts)},')
    print(f'        "fourth_counts": {counter_repr(r.fourth_counts)},')
    print('        "odds": {')
    for team in teams:
        print(odds_repr(team, odds[team]))
    print("        },")
    print("    },")
    print()

print("}")
